### ISSUE TITLE
problem AMRPART +SN

### ISSUE THREAD

**Issue by NicolasDeparis** [domaubert/Quartz#13]
lors d'un run, juste après les 1ères SN, le Lmax a commencé a osciller puis a complètement deraffiné. en même temps, explosion de la sfr. 
amrthresh était a 16
a vérifier!

**Comment by domaubert** [comment]
Je crois que j'ai une idée: je compte bêtement les particules dans la cellule... sauf que si une cellule est raffinée, elle ne contient pas de particules car elles sont distribuées sur ses enfants....ça peut mettre un peu la zone.

A vérifier

**Comment by domaubert** [comment]
fix de la méthode de décompte des particules pour l'AMR en mode AMRPART
Beaucoup plus stable et on retrouve pour l'essentiel les résultats sans AMRPART

à vérifier avec des Supernovaes

**Comment by domaubert** [comment]
ça a l'air ok avec les SNs
