### ISSUE TITLE
Remplacer srcint dans le fichier param par une escape fraction ? 

### ISSUE THREAD

**Issue by domaubert** [domaubert/Quartz#15]
si le flag SRCINT est actif, la valeur d'intensité de source pré-calculée remplace celle du fichier de paramètre, probablement qu'elle pourrait alors être interprété comme une fesc

Ex:
read dummy dans fichier param
# ifdef SRCINT

param->srcint=SRCINT*dummy
# else

param->srcint=dummy
# endif

**Comment by NicolasDeparis** [comment]
Ok, c'est modifié pour fonctionner comme tu le propose.
Mais il serait peut être judicieux d'introduire fesc dans le fichier de param?

**Comment by domaubert** [comment]
dans l'exemple ci dessus :

read dummy dans fichier param
#ifdef SRCINT
param->srcint=SRCINT*dummy
#else
param->srcint=dummy
#endif

quand SRCINT est activé, dummy fait office d'escape fraction
donc à priori pas besoin de paramètre supplémentaire

**Comment by NicolasDeparis** [comment]
c'est pas faux!
closed?
