### ISSUE TITLE
KPCLIMIT seulement si l >lcoarse

### ISSUE THREAD

**Issue by NicolasDeparis** [domaubert/Quartz#25]
Je viens de faire un run en 2Mpc/h L7+0 et a un moment KPCLIMIT c'est enclenché sans raison apparente. 

l'erreur
Blocking refinement to level 8 : dx[8]=3.294685e-05 dxkpc=3.349997e-05
puis
eint=1.831339e-19 nH=1.779585e+02 x0=1.811021e-05 T=4.969159e+01 N=-1.645338e-06
a l'infini

**Comment by domaubert** [comment]
ah oui le gag ! Quelle idée de faire des boites aussi petites :-)

**Comment by NicolasDeparis** [comment]
C'est pour tenter de comparer avec les runs que fait l'autre Nico en ce moment.
Mais en même temps c'est vrai que je n'aurai pas du le laisser, vu que le run était sans raffinement

**Comment by domaubert** [comment]
Cette erreur a été corrigée à priori depuis un moment
Je ferme.
