### ISSUE TITLE
COARSERAD + IC's

### ISSUE THREAD

**Issue by NicolasDeparis** [domaubert/Quartz#26]
J'ai un bug assez bizarre:
Sans COARSERAD, sans raffinement, à un moment la boucle de refroidissement s'emballe avec des :
eint=8.317675e-17 nH=2.353719e+02 x0=7.648709e-04 T=1.705125e+04 N=-5.681915e-06
a l'infini.
Mais a chaque fois que ça pète, juste avant j'ai:
read part =68509 diff p=68509
ce qui est sensé être printer juste après la lecture des conditions initiales.

avec COARSERAD le run se passe bien mais j'ai des 
read part =68509 diff p=68509
de tout les process autre que celui qui est censé faire la lecture, tout a la fin du log.

Je sais pas trop le lien qu'il peut y avoir entre tout ça mais j'ai l'impression qu'il y  a un problème de synchro en sortie des de lecture des IC's

**Comment by domaubert** [comment]
Si c'est sur Curie Je pense qu'il n'y a pas de rapport. 
1/ tous les processus sont censés ecrire le readpart, c'est juste que sur curie, il bufferise les sorties des autres processeurs et les mets à la fin du log
2/ concernant la boucle infinie on voit que N est négatif, c'est la densité de photons, qui doit être positive. En plus elle est plutôt faible. C'est avec le fond UV ?C'est dans quel régime ?
