### ISSUE TITLE
YHE undeclared

### ISSUE THREAD

**Issue by NicolasDeparis** [domaubert/Quartz#30]
src/amr.c: In function ‘L_refine_cells’:
src/amr.c:554:33: error: ‘YHE’ undeclared (first use in this function)
          Wi[il].dX=Wi[il].d_(1.-YHE)_xion;

**Comment by NicolasDeparis** [comment]
Je me suis mis un #define YHE (1) en attendant

**Comment by domaubert** [comment]
Je viens de vérifier dans les dernières versions. Dans param.h, il ya YHE=0.24 ou YHE=0 en fonction du define. Ce sont les bonnes valeurs des paramètres
A priori je ne vois plus de #define YHE (1), ce qui serait une erreur

Pour moi c'est bon
