### ISSUE TITLE
Erreur dans le calcul du Lmin pour le multigrid 

### ISSUE THREAD

**Issue by domaubert** [domaubert/Quartz#31]
Dans emma.c, remplacer 
Lmin= (int) (log(cpu.nproc)/log(2))

par 

Lmin= 1+ int(log(cpu.nproc)/(3*log(2)))

(car Nproc = 2^(3(lmin-1)) et non pas Nproc=2^lmin)

**Comment by NicolasDeparis** [comment]
OK, c'est corrigé. Mais au final j'ai mis: 
Lmin= 1+ int(log(cpu.nproc)/(3*log(2)) +1)
pour arrondir a l'entier supérieur.
